version: '3.3'
services:
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: oitczvovich/news_portal_web:latest
    restart: always
    volumes:
      - static_value:/code/static_backend/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
    - db
    - backend

volumes:
  static_value:
  media_value:
  postgres_data: