# Generated by Django 4.2.4 on 2023-08-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_author_alter_comment_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
