# Generated by Django 4.2.4 on 2023-08-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
